[project]
name = "scietex.log_aggregator_service"
description = "Scietex microservice daemon that aggregates per-worker log streams"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [{ name = "Anton Bondarenko", email = "bond.anton@gmail.com" }]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]
dependencies = [
  "scietex.service[valkey]~=6.1.1",
]
dynamic = ["version"]

[project.urls]
"Bug Tracker" = "https://github.com/bond-anton/scietex.log_aggregator_service/issues"
"Homepage" = "https://github.com/bond-anton/scietex.log_aggregator_service"

[project.scripts]
start-log-aggregator = "scietex.log_aggregator_service.run_worker:main"

[project.optional-dependencies]
dev = ["tox>=4.45.0"]
lint = ["ruff", "ty"]
test = ["pytest", "pytest-asyncio"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.setuptools.dynamic]
version = { attr = "scietex.log_aggregator_service.version.__version__" }

[tool.setuptools.package-data]
"scietex.log_aggregator_service" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]
